spring.application.name=cropadvisor

spring.datasource.url=jdbc:mysql://localhost:3306/cropadvisor
spring.datasource.username=root
spring.datasource.password=Anitha@18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
